### PR TITLE
added Techlahoma Slack channel

### PR DESCRIPTION
**Pull request by dustyjuhl**

### CODE REVIEW

**Comment by ladyleet** [comment]
@dustyjuhl thx! Can you update the description as well on the top to include Oklahoma? Merged :)

**Comment by ladyleet** [comment]
Oh oops not merged... can you resolve the conflicts pls!

**Comment by dustyjuhl** [comment]
Oklahoma is already listed under "The Southwest".

**Comment by ladyleet** [comment]
@dustyjuhl ah thanks! Can you resolve the conflicts?

**Pull request merged**
