### PR TITLE
Add GDG Baroda Slack link

### PR DESCRIPTION
**Pull request by SnehPandya18**
Added GDG Baroda's official Slack group invite link. #38

### CODE REVIEW

**Comment by ladyleet** [comment]
@SnehPandya18 hi! love that there is a GDG Baroda! :) merged!

**Comment by SnehPandya18** [comment]
Indeed! Catch us if you ever visit India, we are consistently active! :)

**Comment by ladyleet** [comment]
@SnehPandya18 actually in bengalaru now and will be speaking at devfest GDG bangalore saturday! :)

**Comment by SnehPandya18** [comment]
Wonderful, just concluded our DevFest Baroda 2017 yesterday, come by if possible anytime!

**Pull request merged**
