### PR TITLE
Add India based Slack channels.

### PR DESCRIPTION
**Pull request by naushad-madakiya**
- Add popular Slack channels like GDG Pune, GDG Ahmedabad, mindorks.
- Reformate section of India based channels.

Fixes: #36

### CODE REVIEW

**Comment by ladyleet** [comment]
@naushad-madakiya thanks! merged

**Comment by naushad-madakiya** [comment]
@ladyleet can you add #hactoberfest label to this issue? This would also encourage other to contribute.

**Comment by ladyleet** [comment]
@naushad-madakiya can you point me to some docs that show me what you actually mean by adding a label?

**Comment by naushad-madakiya** [comment]
@ladyleet repository owner can put label on issue which helps to keep track of the issue. 

Label for issues: https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/
Why #Hactoberfest: https://hacktoberfest.digitalocean.com

**Comment by ladyleet** [comment]
@naushad-madakiya AH! thank you!!!!

**Comment by naushad-madakiya** [comment]
@ladyleet can you add #hactoberfest label to the issue?

**Pull request merged**
