### PR TITLE
Add Callstack OSS

### PR DESCRIPTION
**Pull request by grabbou**
Small typo and adding my Slack. We are based out of Wroclaw and open to discussing anything related to our city.

@ladyleet not sure it fits here :)

### CODE REVIEW

**Comment by ladyleet** [comment]
@grabbou do you guys have a community channel for peeps?

**Comment by grabbou** [comment]
Yeah, we have one channel per every project in open source we do, channel for our conference and everything else

**Comment by ladyleet** [comment]
@grabbou awesome!

**Comment by ladyleet** [comment]
@grabbou merged

**Comment by grabbou** [comment]
Thanks!

**Pull request merged**
