### PR TITLE
Added Kubernetes slack group

### PR DESCRIPTION
**Pull request by ffahri**

### CODE REVIEW

**Comment by 1andee** [comment]
This should perhaps link to http://slack.k8s.io/ so non-members can obtain an invite.

**Comment by ffahri** [comment]
@1andee yes you're right. sorry for wrong link. i changed and commited the changes

**Comment by ladyleet** [comment]
@ffahri thx! Mind resolving conflicts?

**Comment by necoline** [comment]
Thanks @ffahri

**Pull request merged**
