### PR TITLE
Converted to markdown

### PR DESCRIPTION
**Pull request by dovidweisz**
My regex for converting the links :  `<a href="([a-z:/\.0-9\-@]+)">([A-Za-z0-9\. @\(\)\,\-ș]+)</a>`

I just kept adding things until it matched every link LOL

### CODE REVIEW

**Comment by dovidweisz** [comment]
Here is a diff of the generated content:

https://www.diffchecker.com/Vp6JzArY

**Comment by ladyleet** [comment]
@dovidweisz 😢 conflicts because i *slacked* literally on merging this. 🤕  can you please resolve and i'll merge immediately? 🥇

**Comment by dovidweisz** [comment]
Hey,

I figured as much 😂

Is everything else merged?

**Comment by ladyleet** [comment]
@dovidweisz YES!!!! 👍

**Comment by ladyleet** [comment]
@dovidweisz look at us! @EdenSG was so nice to do this for us! <3

**Pull request closed without merging**
