### PR TITLE
Adding emoji flags

### PR DESCRIPTION
**Pull request by tsainte**
Adding emojis so we can make a bit more friendly and colourful. Hope you like it!

### CODE REVIEW

**Comment by ladyleet** [comment]
thank you @tsainte ! love it! can you resolve the conflicts and i'll merge?

**Comment by ladyleet** [comment]
@tsainte pinging you again because WANT! :D

**Comment by tsainte** [comment]
Here it goes! Emojis everywhere 😹

**Comment by ladyleet** [comment]
Thanks @tsainte !

**Pull request merged**
